---
all:
  children:
    CVP:
      hosts:
        cv_ztp:
          ansible_host: 10.83.28.164
          ansible_user: root
          ansible_password: ansible
        cv_server:
          ansible_httpapi_host: 10.83.28.164
          ansible_host: 10.83.28.164
          ansible_user: ansible
          ansible_password: ansible
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_network_os: eos
          ansible_httpapi_port: 443
          # Configuration to get Virtual Env information
          ansible_python_interpreter: $(which python3)
    # DC1_Fabric - EVPN Fabric running in home lab
    Waterloo:
      children:
        WL_DC:
          children:
            WL_DC_Fabric:
              children:
                WL_SPINES:
                  vars:
                    type: spine
                  hosts:
                    WL-SPINE1:
                      ansible_host: 10.2.98.11
                    WL-SPINE2:
                      ansible_host: 10.2.98.12
                WL_LEAFS:
                  vars:
                    type: l3leaf
                  children:
                    WL-POD1:
                      hosts:
                        WL-LEAF1:
                          ansible_host: 10.2.98.20
                        WL-LEAF2:
                          ansible_host: 10.2.98.21
            WL_TENANTS_NETWORKS:
              children:
                WL_LEAFS:
            WL_SERVERS:
              children:
                WL_LEAFS:
    DC1:
      children:
        DC1_FABRIC:
          children:
            DC1_SPINES:
              vars:
                type: spine
              hosts:
                DC1-SPINE1:
                  ansible_host: 10.255.0.11
                DC1-SPINE2:
                  ansible_host: 10.255.0.12
            DC1_L3LEAFS:
              vars:
                type: l3leaf
              children:
                DC1_LEAF1:
                  hosts:
                    DC1-LEAF1A:
                      ansible_host: 10.255.0.13
                    DC1-LEAF1B:
                      ansible_host: 10.255.0.14
                DC1_LEAF2:
                  hosts:
                    DC1-LEAF2A:
                      ansible_host: 10.255.0.15
                    DC1-LEAF2B:
                      ansible_host: 10.255.0.16
            DC1_L2LEAFS:
              vars:
                type: l2leaf
              children:
                DC1_L2LEAF1:
                  hosts:
                    DC1-L2LEAF1A:
                      ansible_host: 10.255.0.17
                DC1_L2LEAF2:
                  hosts:
                    DC1-L2LEAF2A:
                      ansible_host: 10.255.0.18
          vars:
            ansible_connection: httpapi
            ansible_network_os: eos
            ansible_user: ansible
            # should use vault for passwords
            ansible_ssh_pass: ansible
            ansible_become: true
            ansible_become_method: enable
            ansible_httpapi_use_ssl: true
            ansible_httpapi_validate_certs: false
        DC1_TENANTS_NETWORKS:
          children:
            DC1_L3LEAFS:
            DC1_L2LEAFS:
        DC1_SERVERS:
          children:
            DC1_L3LEAFS:
            DC1_L2LEAFS:
