---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: WL_DC_Fabric

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: true

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

# OT Spine Switches
spine:
  defaults:
    platform: DCS-7050CX3-32S
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.100.0/24
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    #mlag_peer_ipv4_pool: 10.255.252.0/24
    #mlag_peer_l3_ipv4_pool: 10.255.251.0/24
  nodes:
    WL-SPINE1:
      id: 1
      mgmt_ip: 10.2.98.11/24
    WL-SPINE2:
      id: 2
      mgmt_ip: 10.2.98.12/24
# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    platform: DCS-7050SX3-48YC8
    loopback_ipv4_pool: 192.168.101.0/24
    loopback_ipv4_offset: 10
    vtep_loopback_ipv4_pool: 192.168.102.0/24
    uplink_interfaces: ['Ethernet49/1', 'Ethernet50/1']
    uplink_switches: ['WL-SPINE1', 'WL-SPINE2']
    uplink_ipv4_pool: 192.168.100.0/24
    mlag_interfaces: [ Ethernet51/1, Ethernet52/1 ]
    mlag_peer_ipv4_pool: 192.168.103.0/24
    mlag_peer_l3_ipv4_pool: 192.168.104.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:01
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    #LACP_PORT_ID_RANGE ONLY AFFECTS UPLINK PORT-CHANNELS
    #lacp_port_id_range:
    #  enabled: true
    #  size: 10000
    #  offset: 10
  node_groups:
    WL-POD1:
      bgp_as: 65101
      nodes:
        WL-LEAF1:
          id: 1
          mgmt_ip: 10.2.98.20/24
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
        WL-LEAF2:
          id: 2
          mgmt_ip: 10.2.98.21/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
    WL-POD2:
      bgp_as: 65102
      nodes:
        WL-LEAF3:
          id: 3
          mgmt_ip: 10.2.98.22/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        WL-LEAF4:
          id: 4
          mgmt_ip: 10.2.98.23/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]

#### Override for vEOS Lab Caveats ####

# Disable update wait-for-convergence and update wait-for-install,
# which is not supported in vEOS-LAB.
# Refer to design guide

# Update p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 9214

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

# List of additional CVP configlets to bind to devices and containers
# Configlets MUST be configured on CVP before running AVD playbooks.

# cv_configlets:
#   containers:
#     DC1_L3LEAFS:
#       - ASE_GLOBAL-ALIASES
