---
port_profiles:
  COMPUTE:
    mode: trunk
    vlans: "2,3,4,2555,2556"
  STORAGE:
    mode: trunk
    vlans: "2556"

servers:
  POD-1-COMPUTE:
    rack: rack1
    adapters:
      - type: nic
        switch_ports: [Ethernet1, Ethernet2]
        switches: [WL-LEAF1, WL-LEAF2]
        profile: COMPUTE
